### PR TITLE
feat: Support short and long usernames in rego

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

*Please add a description here. This will become the commit message of the merge request later.*

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
```

```[tasklist]
# Acceptance
- [ ] Proper release label has been added
```

### CODE REVIEW

**Review by NickLarsenNZ — APPROVED** [review]
I think that makes sense

**Comment by adwk67** [comment]
@sbernauer I don't think the HDFS mapper issues calls with long names, but only short ones, so I'm not sure if the groups-for-users will work with what comes from HDFS. Have we tested that?

**Comment by NickLarsenNZ** [comment]
@adwk67, it looks like it does based on the example payload in the README (hidden in a details block):

image

**Comment by adwk67** [comment]
@NickLarsenNZ I mean what comes from here: I think that is just the short name: https://github.com/stackabletech/hdfs-utils/blob/main/src/main/java/tech/stackable/hadoop/StackableGroupMapper.java#L73. I'm probably missing something but I don't see where we resolve that against the UGI.

**Comment by NickLarsenNZ** [comment]
@adwk67, good point - I didn't consider the Group Mapper code when approving.
@sbernauer, will the Group Mapper code be updated to provide additional context?

**Comment by sbernauer** [comment]
Well that's a pity... `public List<String> getGroups(String user) {` only seems to give the shortName and not the full name, making it impossible to return the correct groups in this case if I understood correctly

**Pull request merged**
