### PR TITLE
feat: Introduce maven profile to build against Hadoop 3.3.4, 3.3.6 or 3.4.0

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

*Please add a description here. This will become the commit message of the merge request later.*

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
```

```[tasklist]
# Acceptance
- [ ] Proper release label has been added
```

### CODE REVIEW

**Review by labrenbe — DISMISSED** [review]
lgtm

**Review by labrenbe — DISMISSED** [review]
lgtm

**Review by labrenbe — DISMISSED** [review]
lgtm

**Review by labrenbe — APPROVED** [review]
lgtm

**Comment by lfrancke** [comment]
It's too late now but you can look at the Druid OPA Authorizer how this can be modeled
https://github.com/stackabletech/druid-opa-authorizer

**Comment by sbernauer** [comment]
This looks exactly the same way I did it :sweat_smile:  I assume you mentioned this for context, and not because you found a difference or dislike the current state?

**Pull request merged**
